
name: Build apk

on:
  push:
    branches:
      - main
jobs:
  apk:
    name: Generate IPA
    runs-on: macOS-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1
        
      - uses: yukiarrr/ios-build-action@v1.5.0
        with:
          project-path: merchandiseios.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          ertificate-password: "123456"
          team-id: ${{ secrets.TEAM_ID }}
          #workspace-path: Unity-iPhone.xcworkspace # optional

